name: Production Build

on:
  push:
    branches:
      - cerritus-adaptions
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build release
        uses: ./.github/actions/build-release
        with:
          release_access_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
