name: Production Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  production-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt update
    - run: sudo apt -y install libkrb5-dev
    - run: cp config.json.example config.json
    - name: npm install
      run: |
        npm install
      env:
        CI: true
        NODE_ENV: production
